### PR TITLE
chore: Add recommended extensions and debug configuration

### PR DESCRIPTION
**Pull request by tolusha**

### CODE REVIEW

**Comment by tolusha** [comment]
Hello, @kadel
Could you have a look?

**Comment by tolusha** [comment]
Could you merge please? I don't have `merge` button.

**Comment by tolusha** [comment]
@kadel 
Could you merge please?

**Review by kadel — APPROVED** [review]

**Comment by kadel** [comment]
Surprisingly I don't have write access to this repo :-( I'm even no longer a devfile-samples member :-(

**Pull request merged**
